#!/usr/bin/env bash
set -e

PROTO_DIR="./protos"
OUTPUT_DIR="./generated"
PROTOC_ARGS="--python_out=$OUTPUT_DIR --grpc_out=$OUTPUT_DIR --plugin=protoc-gen-grpc=`which grpc_python_plugin`"

command -v protoc >/dev/null 2>&1 || {
  echo "protoc not found!"
  echo "Install protocol buffers and grpc before continuing."
  echo "http://www.grpc.io/docs/tutorials/basic/python.html"
  exit 1
}

mkdir -p $OUTPUT_DIR

for PROTO in $(find $PROTO_DIR -name "*.proto"); do
  echo "generating: $PROTO"
  protoc -I $PROTO_DIR $PROTOC_ARGS $PROTO
done

echo "done."
