#!/bin/bash

set -e

WORKDIR="/grpc"
DEST="/usr/local/bin"

git clone https://github.com/grpc/grpc.git $WORKDIR
cd $WORKDIR
git submodule update --init
make grpc_python_plugin
cp bins/opt/grpc_python_plugin $DEST
