#!/bin/bash

set -e

WORKDIR="./grpc"
DEST="/usr/local/bin"

git clone https://github.com/grpc/grpc.git $WORKDIR
cd $WORKDIR
git submodule update --init
make plugins
cp ./bins/opt/grpc_python_plugin $DEST
cp ./bins/opt/protobuf/protoc $DEST
cd /
rm -rf $WORKDIR
