#!/bin/bash

set -e

echo "installing protoc";

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORK_DIR="$SCRIPT_DIR/bin"
DEST="/usr/local/bin/protoc"

if [ ! -f $DEST ]; then
  if [ ! -d "$WORK_DIR" ]; then
    mkdir -p "$WORK_DIR"
  fi

  PROTOC_FILE_NAME="protoc-3.0.0-beta-2-linux-x86_64.zip"

  if [[ "$OSTYPE" == "darwin"* ]]; then
    PROTOC_FILE_NAME="protoc-3.0.0-beta-2-osx-x86_64.zip"
  fi

  PROTOC_PATH="$WORK_DIR/$PROTOC_FILE_NAME"

  curl -Lk "https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/$PROTOC_FILE_NAME" -o "$PROTOC_PATH"

  unzip "$PROTOC_PATH" -d "$WORK_DIR"
  chmod a+x "$WORK_DIR/protoc"

  mv "$WORK_DIR/protoc" $DEST

  echo "protoc installed in: $DEST"
else
  echo "protoc already installed at $DEST"
fi
